/**
 * ARCA
 * Aqui descripcion de la api
 *
 * OpenAPI spec version: 0.0.1
 * Contact: no hay
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CarnetVacunacion } from './carnetVacunacion';
import { FichaClinica } from './fichaClinica';

export interface Animal { 
   observacionesProcedencia?: string;
    colorCaracteristicas?: string;
    edad?: number;
    especie?: string;
    fechaNacimiento?: Date;
    fichasClinicas?: Array<FichaClinica>;
    foto?: string;
    historialVacunaciones?: Array<CarnetVacunacion>;
    id?: number;
    lugarEstancia?:string;
    nombre?: string;
    peso?: number;
    raza?: string;
    sexo?: string;
    procedencia?:string;
    tamanyo?: string;
}