/**
 * ARCA
 * Aqui descripcion de la api
 *
 * OpenAPI spec version: 0.0.1
 * Contact: no hay
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Animal } from './animal';
import { Veterinario } from './veterinario';

export interface FichaClinica { 
    alimentacion?: number;
    animal: Animal;
    conjuntiva?: string;
    costo?: number;
    diagnosticoDiferencial?: string;
<<<<<<< HEAD
    esterilizacion?: string; 
=======
    esterilizacion: string;
    examenesSolicitados?: string;
>>>>>>> d91bca2ff3ccc0055e45abe5903c0509ada220e4
    fechaIngreso?: Date;
    frecuenciaCardiaca?: number;
    frecuenciaRespiratoria?: number;
    hallazgos?: string;
    id?: number;
    motivoConsulta?: string;
    mucosas?: string;
    pronostico?: string;
    temperatura?: number;
    tipoPaciente?: string;
    trc?: string;
    veterinario?: Veterinario;
    animal?:Animal;
    examenes_solicitados?: string;
    tipoPaciente?:string;
}
