export * from './adopcionController.service';
import { AdopcionControllerService } from './adopcionController.service';
export * from './adoptanteController.service';
import { AdoptanteControllerService } from './adoptanteController.service';
export * from './animales.service';
import { AnimalesService } from './animales.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './citas.service';
import { CitasService } from './citas.service';
export * from './fichasClnicas.service';
import { FichasClnicasService } from './fichasClnicas.service';
export * from './medicaciones.service';
import { MedicacionesService } from './medicaciones.service';
export * from './medicamentos.service';
import { MedicamentosService } from './medicamentos.service';
export * from './personas.service';
import { PersonasService } from './personas.service';
export * from './servicios.service';
import { ServiciosService } from './servicios.service';
export * from './tratamientos.service';
import { TratamientosService } from './tratamientos.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './vacunas.service';
import { VacunasService } from './vacunas.service';
export * from './veterinarios.service';
import { VeterinariosService } from './veterinarios.service';
export const APIS = [AdopcionControllerService, AdoptanteControllerService, AnimalesService, AuthControllerService, CitasService, FichasClnicasService, MedicacionesService, MedicamentosService, PersonasService, ServiciosService, TratamientosService, UserControllerService, VacunasService, VeterinariosService];
